//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights_Yarullin.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public Airplane()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int Id_airplane { get; set; }
        public string Name_airplane { get; set; }
        public Nullable<int> number_seats { get; set; }
        public int Id_type { get; set; }
    
        public virtual Type_Airplane Type_Airplane { get; set; }
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
