//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights_Yarullin.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airticket
    {
        public int Id_airticket { get; set; }
        public string Place { get; set; }
        public string Price { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_booking { get; set; }
        public Nullable<int> Id_type_airticket { get; set; }
        public Nullable<int> Id_flight { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual TypeAirticket TypeAirticket { get; set; }
        public virtual User User { get; set; }
    }
}
