//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights_Yarullin.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Airticket = new HashSet<Airticket>();
        }
    
        public int Id_flight { get; set; }
        public Nullable<System.DateTime> Departure_date_time { get; set; }
        public Nullable<System.DateTime> Arrival_date_time { get; set; }
        public string Dispatch_city { get; set; }
        public string Arrival_city { get; set; }
        public int Id_airplane { get; set; }
        public int Id_airline { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airplane Airplane { get; set; }
        public virtual ICollection<Airticket> Airticket { get; set; }
    }
}
