//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights_Yarullin.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAirticket
    {
        public TypeAirticket()
        {
            this.Airticket = new HashSet<Airticket>();
        }
    
        public int Id_type_airticket { get; set; }
        public string Name_type { get; set; }
    
        public virtual ICollection<Airticket> Airticket { get; set; }
    }
}
